### PR TITLE
Fix auto-setting of `created_by` field on Task creation (#23)

### LINKED ISSUE #23: created_by not automatical set when task is created

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #23.

### Summary of Changes
Fixes auto-setting of `created_by` in the responsible TaskTable::save() method. Also improves docs and cleans up the class.

### Testing Instructions
Create a new task and check if the `created_by` (user) field reflects in the form.

### Actual result BEFORE applying this Pull Request
`created_by` doesn't get set correctly.

### Expected result AFTER applying this Pull Request
`created_by` gets set correctly.

### CODE REVIEW

File: administrator/components/com_scheduler/src/Table/TaskTable.php [hunk 1]
```diff
@@ -1,78 +1,83 @@
...
+ * @subpackage  com_scheduler
  *
- * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
- * @license       GNU General Public License version 2 or later; see LICENSE.txt
+ * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
+ * @license     GNU General Public License version 2 or later; see LICENSE.txt
  */
 
-/** Implements the Table class for com_scheduler.tasks. */
+/** phpcs:disable Joomla.NamingConventions.ValidVariableName.MemberNotCamelCaps,Joomla.NamingConventions.ValidVariableName.ClassVarHasUnderscore,Joomla.NamingConventions.ValidFunctionName.MethodUnderscore */
```
Comment (ditsuke) [inline administrator/components/com_scheduler/src/Table/TaskTable.php:10]: todo: remove
